<?php
/**
 * SuccessfulResponseWithWarningTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Liquipedia\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LiquipediaDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Liquipedia\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SuccessfulResponseWithWarningTest Class Doc Comment
 *
 * @category    Class
 * @description SuccessfulResponseWithWarning
 * @package     Liquipedia\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SuccessfulResponseWithWarningTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SuccessfulResponseWithWarning"
     */
    public function testSuccessfulResponseWithWarning()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "warning"
     */
    public function testPropertyWarning()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
