name: Lint style

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dprint/check@v2.2
