<?php
/**
 * V3ApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Liquipedia\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LiquipediaDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Liquipedia\Client\Test\Api;

use \Liquipedia\Client\Configuration;
use \Liquipedia\Client\ApiException;
use \Liquipedia\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * V3ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Liquipedia\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V3ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadcastersGet
     *
     * Get broadcasters.
     *
     */
    public function testBroadcastersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companyGet
     *
     * Get companies.
     *
     */
    public function testCompanyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for datapointGet
     *
     * Get datapoints.
     *
     */
    public function testDatapointGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for externalmedialinkGet
     *
     * Get media links.
     *
     */
    public function testExternalmedialinkGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for matchGet
     *
     * Get matches.
     *
     */
    public function testMatchGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placementGet
     *
     * Get placements.
     *
     */
    public function testPlacementGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGet
     *
     * Get players.
     *
     */
    public function testPlayerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for seriesGet
     *
     * Get series.
     *
     */
    public function testSeriesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for squadplayerGet
     *
     * Get squadplayer.
     *
     */
    public function testSquadplayerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for standingsentryGet
     *
     * Get standing.
     *
     */
    public function testStandingsentryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for standingstableGet
     *
     * Get standing.
     *
     */
    public function testStandingstableGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for teamGet
     *
     * Get teams.
     *
     */
    public function testTeamGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for teamtemplateGet
     *
     * Get a team template.
     *
     */
    public function testTeamtemplateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for teamtemplatelistGet
     *
     * Get a list of team templates.
     *
     */
    public function testTeamtemplatelistGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tournamentGet
     *
     * Get tournaments.
     *
     */
    public function testTournamentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferGet
     *
     * Get transfers.
     *
     */
    public function testTransferGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
